name: Update PR Template

on:
  pull_request:
    types: [opened]
    
jobs:
  update-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set variables
        run: |
          PR_TITLE="New title"
          PR_DESCRIPTION="New description"
          PR_ASSIGNEE="@assignee"
          COMMIT_MESSAGE="Update PR template"

      - name: Update PR Template
        run: |
          sed -i "s/DESCRIPTION_PLACEHOLDER/$PR_DESCRIPTION/g" .github/pull_request_template.md
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

     
