name: Update PR Template

on:
  pull_request:
    types: [opened, edited]

jobs:
  update_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Update PR Template Description
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('pull_request_template.md', 'utf8');
            const newContent = content.replace(/## Description.*?(?=##|\n\n)/s, '## Description\n\nThis is a dynamically updated description!');
            fs.writeFileSync('pull_request_template.md', newContent);
            console.log('Updated PR Template Description.');
