name: Update PR Template

on:
  push:
    branches:
      - main

jobs:
  update-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set variables
        run: |
          PR_TITLE="New title"
          PR_DESCRIPTION="New description"
          PR_ASSIGNEE="@assignee"
          COMMIT_MESSAGE="Update PR template"

      - name: Update PR Template
        run: |
          sed -i "s/DESCRIPTION_PLACEHOLDER/$PR_DESCRIPTION/g" .github/PULL_REQUEST_TEMPLATE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git add .
          git -c user.name='GitHub Actions' -c user.email='actions@github.com' commit -m "$COMMIT_MESSAGE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
