#!/bin/sh
check=$(head -1 $1 | grep -e '[A-Z]\+-[0-9]\+')
if [ "" = "$check" ]; then
        echo "Commit message should have jira ticket id." 1>&2
        echo "Required format is" 1>&2
        echo "    [ticketid] <description>" 1>&2
        exit 1
fi