on:
  push:
    branches:
      - 'release/**'
      
jobs:
  notify-slack:
    runs-on: ubuntu-latest
   # needs: build-test
  #  if: ${{ always() }}
    steps:
      - name: Notify Slack on success
       # if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
              --data '{"text": "Python app build and test succeeded from release branch"}' \
              $SLACK_WEBHOOK_URL
