name: Update Confluence table

on:
  push:
    branches:
      - master

jobs:
  update-confluence-table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install -g httpie jq

      - name: Update Confluence table
        env:
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
          CONFLUENCE_API_URL: "https://demositefirst.atlassian.net/wiki/rest/api/content"
          PAGE_ID: "294913"
        run: |
       
          curl --request GET --url 'https://demositefirst.atlassian.net/wiki/rest/api/content/294913' --user 'aartibh@cybage.com:$CONFLUENCE_API_TOKEN' --header 'Accept: application/json'

        
