on:
  push:
    branches:
      - '*'
      
jobs:
  notify-slack:
    runs-on: ubuntu-latest
   # needs: build-test
    steps:
      - name: Send Slack notification on release branch
        if: contains('refs/heads/release/', github.ref)
        uses: slackapi/slack-github-action@v1.23.0
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,action,workflow,job,took
         # channel: "#your-slack-channel"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#         run: |
#           curl -X POST -H 'Content-type: application/json' \
#           --data '{"text": "Hello Workflow for release branch:  ${{ github.workflow }} has ${{ job.status }}."}' \
#           $SLACK_WEBHOOK_URL
          
      - name: Send Slack notification on feature branch
        if: startsWith(github.ref, 'refs/heads/feature/')
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CHANNEL2 }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Hello Workflow for feature branch: ${{ github.workflow }} has ${{ job.status }}."}' \
          $SLACK_WEBHOOK_URL
          
   

