name: Update Confluence Page

on:
  push:
    branches:
      - master

jobs:
  confluence-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y curl

      - name: Create Page
        env:
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
        run: |
              curl --request PUT \
                --url 'https://kanishkpadhi.atlassian.net/wiki/api/v2/pages/524325' \
                --user 'kaniskan@cybage.com:ATATT3xFfGF0bwhn0eHVaCqG5Ft_NKi8a6urQXbhJPqf4_yR_bkSU16TUaX3pPmsPGlAePrBFV-6T-3fIAidvB-Zcgr6VgFPTHbRsUgzSf_J_vKJcyBr0CVViSADB5XKZIz2Viiwrj2JZXgXGy05wyld3agVBY40gFthNGtcKX0s9o08RLQexXg=B3FC49D2' \
                --header 'Accept: application/json' \
                --header 'Content-Type: application/json' \
                --data '{
                "id": "524325",
                "status": "current",
                "title": "Hello!",
                "spaceId": "33071",
                "body": {
                  "representation": "storage",
                  "value": "<table><tr><th>Artifact Version</th><th>Date</th></tr><tr><td>'1.0.0'</td><td>'11-May-2023'</td></tr></table>"
                }
              }'
