on:
  push:
    branches:
      - '*'
      
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification on release branch
        if: contains(github.ref, 'release')
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          COMMIT_ID: ${{ github.sha }}
#           GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB}}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": " Workflow updates:\n  Status: ${{ job.status }} \n Triggered by: ${{ github.actor }} \n Event: ${{ github.event_name }} branch: ${{ github.ref }}  Commit: - <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}> workflow action: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>"}' \
          $SLACK_WEBHOOK_URL
          
      - name: Send Slack notification on feature branch
        if: startsWith(github.ref, 'feature')
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CHANNEL2 }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Hello Workflow for feature branch: ${{ github.workflow }} has ${{ job.status }}."}' \
          $SLACK_WEBHOOK_URL
          
   

