on:
  push:
    branches:
      - '*'
      
jobs:
  notify-slack:
    runs-on: ubuntu-latest
   # needs: build-test
  #  if: ${{ always() }}
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Hello Workflow ${{ github.workflow }} has ${{ job.status }}."}' \
          $SLACK_WEBHOOK_URL

