on:
  push:
    branches:
      - '*'
      
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification on release branch
        if: contains(github.ref, 'release')
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              'repository.git_commits_url': 'https://api.github.com/repos/ALMCybage/Python-Project-Demo/git/commits{/sha}',
              'repository.statuses_url': 'https://api.github.com/repos/ALMCybage/Python-Project-Demo/statuses/{sha}',
              'sender.url': 'https://api.github.com/users/aartibh'
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#         run: |
#           curl -X POST -H 'Content-type: application/json' \
#           --data '{"text": "Hello Workflow for release branch:  ${{ github.workflow }} has ${{ job.status }}."}' \
#           $SLACK_WEBHOOK_URL
          
      - name: Send Slack notification on feature branch
        if: startsWith(github.ref, 'feature')
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CHANNEL2 }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "Hello Workflow for feature branch: ${{ github.workflow }} has ${{ job.status }}."}' \
          $SLACK_WEBHOOK_URL
          
   

