name: Create Confluence Page

on:
  push:
    branches:
      - master

jobs:
  get-confluence-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y curl

      - name: Create Page
        env:
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
        run: |
              curl --request POST \
                --url 'https://kanishkpadhi.atlassian.net/wiki/api/v2/pages' \
                --user 'kaniskan@cybage.com:$CONFLUENCE_TOKEN' \
                --header 'Accept: application/json' \
                --header 'Content-Type: application/json' \
                --data '{
                "spaceId": "33071",
                "status": "current",
                "title": "Hello World!",
                "parentId": "33154",
                "body": {
                  "representation": "storage",
                  "value": "<table><tr><th>Artifact Version</th><th>Date</th></tr><tr><td>'1.0.0'</td><td>'11-May-2023'</td></tr></table>"
                }
              }'
