name: Get Confluence data

on:
  push:
    branches:
      - master

jobs:
  get-confluence-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y curl jq

      - name: Get Confluence data
        env:
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
          CONFLUENCE_API_URL: "https://demositefirst.atlassian.net/wiki/rest/api/content"
        run: |
          # Get the list of spaces
          curl --fail --silent --show-error -H "Authorization: Bearer $CONFLUENCE_API_TOKEN" -X GET "$CONFLUENCE_API_URL?expand=space" | jq .

          # Get the content of a page
          curl --fail --silent --show-error -H "Authorization: Bearer $CONFLUENCE_API_TOKEN" -X GET "$CONFLUENCE_API_URL/294913?expand=body.storage" | jq .
